import * as cdk from 'aws-cdk-lib';
import * as cognito from 'aws-cdk-lib/aws-cognito';
import * as events from 'aws-cdk-lib/aws-events';
import * as iam from 'aws-cdk-lib/aws-iam';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { IConstruct } from 'constructs';

/**
 * Configuration for the ResourceTaggerAspect
 */
export interface ResourceTaggerConfig {
  /**
   * The primary tag key to apply
   * @example 'Environment'
   */
  readonly tagKey: string;

  /**
   * The primary tag value to apply
   * @example 'production', 'staging', 'development', 'default'
   */
  readonly tagValue: string;

  /**
   * Additional tags to apply as key-value pairs
   *
   * Optional. When provided, these tags will be applied
   * to all target resources in addition to the primary tag.
   *
   * @example { 'Project': 'GenAI-Web', 'CostCenter': 'engineering' }
   */
  readonly additionalTags?: Record<string, string>;
}

/**
 * Aspect that ensures L1 (Cfn*) resources with non-standard tag properties
 * receive the required tags.
 *
 * This Aspect handles resources that don't follow the standard CDK tagging:
 * - CfnIdentityPool: Uses `identityPoolTags` instead of `tags`
 *
 * Most L1 resources with standard `tags` property are handled by
 * `cdk.Tags.of(scope).add()` and don't need this Aspect.
 *
 * ## Non-Taggable Resources (AWS Specification)
 *
 * The following resource types do NOT support tags by AWS design.
 * These are excluded from tagging and this is expected behavior:
 *
 * ### API Gateway
 * - `AWS::ApiGateway::Method` - API method definitions
 * - `AWS::ApiGateway::Resource` - API resource path definitions
 * - `AWS::ApiGateway::Authorizer` - API authorization settings
 * - `AWS::ApiGateway::GatewayResponse` - Gateway response definitions
 * - `AWS::ApiGateway::Account` - API account settings
 * - `AWS::ApiGateway::Deployment` - API deployments
 *
 * ### Lambda
 * - `AWS::Lambda::Permission` - Lambda execution permissions
 *
 * ### IAM
 * - `AWS::IAM::Policy` - Inline IAM policies (managed policies support tags)
 *
 * ### S3 / SQS
 * - `AWS::S3::BucketPolicy` - Bucket policies
 * - `AWS::SQS::QueuePolicy` - Queue policies
 *
 * ### KMS
 * - `AWS::KMS::Alias` - KMS key aliases
 *
 * ### WAFv2
 * - `AWS::WAFv2::WebACLAssociation` - WebACL associations
 * - `AWS::WAFv2::LoggingConfiguration` - WAF logging configurations
 *
 * ### CloudFront
 * - `AWS::CloudFront::OriginAccessControl` - Origin access control
 * - `AWS::CloudFront::ResponseHeadersPolicy` - Response header policies
 *
 * ### Cognito
 * - `AWS::Cognito::UserPoolClient` - User pool clients
 * - `AWS::Cognito::UserPoolGroup` - User pool groups
 * - `AWS::Cognito::LogDeliveryConfiguration` - Log delivery settings
 * - `AWS::Cognito::IdentityPoolRoleAttachment` - Identity pool role attachments
 *
 * ### EC2
 * - `AWS::EC2::SubnetRouteTableAssociation` - Subnet-route table associations
 * - `AWS::EC2::Route` - Route definitions
 * - `AWS::EC2::VPCGatewayAttachment` - VPC gateway attachments
 *
 * ### CDK Internal Resources
 * - `AWS::CDK::Metadata` - CDK metadata
 * - `Custom::*` - Custom resource providers (auto-generated by CDK)
 *
 * @example
 * ```typescript
 * import { ResourceTaggerAspect } from './lib/aspect/resource-tagger';
 *
 * // Apply to a stack
 * cdk.Aspects.of(stack).add(
 *   new ResourceTaggerAspect({
 *     tagKey: 'Environment',
 *     tagValue: params.appEnv ?? 'default'
 *   })
 * );
 * ```
 */
export class ResourceTaggerAspect implements cdk.IAspect {
  constructor(private readonly config: ResourceTaggerConfig) {}

  /**
   * Visit a construct in the construct tree.
   * Called by CDK's Aspect invocation mechanism.
   *
   * @param node - The construct being visited
   */
  public visit(node: IConstruct): void {
    // Handle CfnFunction (AWS::Lambda::Function)
    // This includes CustomResourceProvider Lambda functions that Tags.of() cannot reach
    if (node instanceof lambda.CfnFunction) {
      this.tagCfnFunction(node);
      return;
    }

    // Handle CfnRole (AWS::IAM::Role)
    // This includes CustomResourceProvider IAM roles that Tags.of() cannot reach
    if (node instanceof iam.CfnRole) {
      this.tagCfnRole(node);
      return;
    }

    // Handle CfnRule (AWS::Events::Rule)
    // EventBridge rules in GenerativeAiUseCasesStack/SourceStack
    if (node instanceof events.CfnRule) {
      this.tagCfnRule(node);
      return;
    }

    // Handle CfnIdentityPool with non-standard 'identityPoolTags' property
    if (node instanceof cognito.CfnIdentityPool) {
      this.tagIdentityPool(node);
      return;
    }

    // Handle generic CfnResource instances (e.g., CustomResourceProvider Lambda/Role)
    // These are created using new CfnResource() with type string, not typed L1 classes
    if (node instanceof cdk.CfnResource) {
      this.tagGenericCfnResource(node);
      return;
    }
  }

  /**
   * Apply tags to CfnFunction using TagManager
   */
  private tagCfnFunction(fn: lambda.CfnFunction): void {
    this.applyTagsViaTagManager(fn.tags, this.config.tagKey, this.config.tagValue);
    this.applyAdditionalTagsViaTagManager(fn.tags);
  }

  /**
   * Apply tags to CfnRole using TagManager
   */
  private tagCfnRole(role: iam.CfnRole): void {
    this.applyTagsViaTagManager(role.tags, this.config.tagKey, this.config.tagValue);
    this.applyAdditionalTagsViaTagManager(role.tags);
  }

  /**
   * Apply tags to CfnRule using addPropertyOverride
   * Note: CfnRule doesn't expose tags via TagManager, so we use addPropertyOverride
   */
  private tagCfnRule(rule: events.CfnRule): void {
    const tagsToApply: Array<{ Key: string; Value: string }> = [];

    // Add primary tag
    tagsToApply.push({ Key: this.config.tagKey, Value: this.config.tagValue });

    // Add additional tags
    if (this.config.additionalTags) {
      for (const [key, value] of Object.entries(this.config.additionalTags)) {
        tagsToApply.push({ Key: key, Value: value });
      }
    }

    rule.addPropertyOverride('Tags', tagsToApply);
  }

  /**
   * Apply a single tag via TagManager, preserving existing tags
   */
  private applyTagsViaTagManager(
    tagManager: cdk.TagManager,
    tagKey: string,
    tagValue: string,
  ): void {
    const existingTags = tagManager.tagValues();
    if (!(tagKey in existingTags)) {
      tagManager.setTag(tagKey, tagValue);
    }
  }

  /**
   * Apply additional tags via TagManager, preserving existing tags
   */
  private applyAdditionalTagsViaTagManager(tagManager: cdk.TagManager): void {
    if (!this.config.additionalTags) {
      return;
    }

    const existingTags = tagManager.tagValues();
    for (const [key, value] of Object.entries(this.config.additionalTags)) {
      if (!(key in existingTags)) {
        tagManager.setTag(key, value);
      }
    }
  }

  /**
   * Apply tags to generic CfnResource instances that support Tags property
   * Used for CustomResourceProvider Lambda functions and IAM roles
   */
  private tagGenericCfnResource(resource: cdk.CfnResource): void {
    const resourceType = resource.cfnResourceType;

    // Only tag resources that support Tags property
    const taggableResourceTypes = ['AWS::Lambda::Function', 'AWS::IAM::Role', 'AWS::Events::Rule'];

    if (!taggableResourceTypes.includes(resourceType)) {
      return;
    }

    const tagsToApply: Array<{ Key: string; Value: string }> = [];

    // Add primary tag
    tagsToApply.push({ Key: this.config.tagKey, Value: this.config.tagValue });

    // Add additional tags
    if (this.config.additionalTags) {
      for (const [key, value] of Object.entries(this.config.additionalTags)) {
        tagsToApply.push({ Key: key, Value: value });
      }
    }

    resource.addPropertyOverride('Tags', tagsToApply);
  }

  /**
   * Apply tag to CfnIdentityPool using identityPoolTags property
   */
  private tagIdentityPool(identityPool: cognito.CfnIdentityPool): void {
    const existingTags = identityPool.identityPoolTags ?? [];

    // Apply primary tag
    const hasPrimaryTag = existingTags.some(
      (tag: { key: string }) => tag.key === this.config.tagKey,
    );
    const tagsToAdd: Array<{ key: string; value: string }> = [];

    if (!hasPrimaryTag) {
      tagsToAdd.push({ key: this.config.tagKey, value: this.config.tagValue });
    }

    // Apply additional tags
    if (this.config.additionalTags) {
      for (const [key, value] of Object.entries(this.config.additionalTags)) {
        const hasTag = existingTags.some((tag: { key: string }) => tag.key === key);
        if (!hasTag) {
          tagsToAdd.push({ key, value });
        }
      }
    }

    if (tagsToAdd.length > 0) {
      identityPool.identityPoolTags = [...existingTags, ...tagsToAdd];
    }
  }
}
