name: バグレポート
description: バグの詳細について記載してください。
title: "バグの概要"
labels: [bug]
assignees: "-"
body:
  - type: checkboxes
    attributes:
      label: 事前確認（1/2）
      options:
        - label: README.mdの「Issue / Pull Request の対応方針」を確認しましたか
          required: true
  - type: checkboxes
    attributes:
      label: 事前確認（2/2）
      options:
        - label: Issuesに同一のバグレポートがないか確認しましたか
          required: true
  - type: textarea
    id: overview
    attributes:
      label: バグ概要
      description: 再現手順、バグの概要、期待される結果を記載してください。（必要に応じて画像を添付してください。）
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: バグが再現したOS
      multiple: true
      options:
        - Windows
        - macOS
        - Android
        - iOS
        - Linux
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: バグが再現したブラウザ
      multiple: true
      options:
        - Google Chrome
        - Microsoft Edge
        - Safari
        - Firefox
  - type: input
    id: version
    attributes:
      label: バグが再現したブラウザのバージョン
      placeholder: "例: 143.0.7499.170（公式ビルド） （arm64）"
    validations:
      required: true
