import mermaid, { type MermaidConfig } from 'mermaid';
import { useCallback, useEffect, useState } from 'react';

const defaultConfig: MermaidConfig = {
  // syntax error が dom node に勝手に追加されないようにする
  // https://github.com/mermaid-js/mermaid/pull/4359
  suppressErrorRendering: true,
  securityLevel: 'antiscript', // SVGのレンダリングを許可
  fontFamily: 'monospace', // フォントファミリーを指定
  fontSize: 16, // フォントサイズを指定
  htmlLabels: true, // HTMLラベルを許可
};

mermaid.initialize(defaultConfig);

type Props = {
  code: string;
  isZoom?: boolean;
  handler?: () => void;
};

export const Mermaid = (props: Props) => {
  const { code, isZoom = false } = props;

  const [svgContent, setSvgContent] = useState<string>('');

  const render = useCallback(async () => {
    if (!code) {
      return;
    }

    try {
      // 一意な ID を指定する必要あり
      const { svg } = await mermaid.render(`m${crypto.randomUUID()}`, code);
      // SVG文字列をパースしてDOMオブジェクトに変換
      const parser = new DOMParser();
      const doc = parser.parseFromString(svg, 'image/svg+xml');
      const svgElement = doc.querySelector('svg');

      if (svgElement) {
        // SVG要素に必要な属性を設定
        svgElement.setAttribute('width', '100%');
        svgElement.setAttribute('height', '100%');
        setSvgContent(svgElement.outerHTML);
      }
    } catch (error) {
      console.error(error);
      setSvgContent(
        '<div>図の作成に失敗しました。お手数をおかけしますが再度お試しください。</div>',
      );
    }
  }, [code]);

  useEffect(() => {
    render();
  }, [code, render]);

  if (!code) {
    return null;
  }

  if (isZoom) {
    return (
      <div className='flex min-h-full min-w-full content-center items-center justify-center rounded-8 bg-white p-8'>
        <div
          className='flex min-h-full min-w-full items-center justify-center'
          // biome-ignore lint/security/noDangerouslySetInnerHtml: SVG content generated by mermaid, which is sanitized by defaultConfig
          dangerouslySetInnerHTML={{ __html: svgContent }}
        />
      </div>
    );
  } else {
    return (
      <button
        type='button'
        aria-label='画像を拡大表示'
        onClick={props.handler}
        className={`flex h-full w-full cursor-zoom-in content-center items-center justify-center rounded-8 bg-white p-8 hover:outline-2 hover:outline-black hover:outline-solid focus-visible:ring-[calc(2/16*1rem)] focus-visible:ring-yellow-300 focus-visible:outline-4 focus-visible:outline-offset-[calc(2/16*1rem)] focus-visible:outline-black focus-visible:outline-solid`}
      >
        <span
          className='flex h-full w-full items-center justify-center'
          // biome-ignore lint/security/noDangerouslySetInnerHtml: SVG content generated by mermaid, which is sanitized by defaultConfig
          dangerouslySetInnerHTML={{ __html: svgContent }}
        />
      </button>
    );
  }
};
